fixup some dependencies
ianpogi5/mocha-badge-generator pull request #37
Opened 2022-09-29 22:35 UTC by DinoChiesa

- move es6-template-strings from devDependencies to dependencies in package.json. It is required by users of this module at runtime, not only for developers of this module.

- add an engines field in package.json, and specify npm 8.3.0 because we will use the overrides feature.

- use an overrides field in package.json to override some vulnerable and outdated modules.

- update required mocha to 10.0.0 to avoid some vulnerable dependencies of earlier versions of mocha.

2022-09-30 05:28 UTC, brettz9 requested changes
Looks good, thank you. If you could just adapt per the comments...

2022-09-30 05:28 UTC, brettz9 commented on package.json
> +        "badge-up": "https://registry.npmjs.org/@rpl/badge-up/-/badge-up-3.0.0.tgz",
I think this should work:

```suggestion
        "badge-up": "npm:@rpl/badge-up@3.0.0",
```

2022-09-30 05:28 UTC, brettz9 commented on package.json
> +    "engines": {
There is already an `engines` property, so if you could add these there instead...

2022-10-02 00:45 UTC, merged

2022-10-02 00:59 UTC, brettz9 commented
@ianpogi5 : Could you publish a new version? npm now requires 2FA, and although I set it up for myself, apparently successfully, it says I don't have permission after correctly entering the One-Time Password (OTP).

2022-10-12 00:04 UTC, brettz9 commented
@ianpogi5 : Do you think you could take a look?

2022-10-12 02:05 UTC, brettz9 commented
@ianpogi5 : After the merge, I guess it will be ready for the stable 0.10.3 release?

2022-10-12 02:11 UTC, ianpogi5 commented
I'll do a release for you this time but I'll take a screenshot on what I did. 

Yes you should study GA. I make your life easier.